import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Travel Guide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>

        {children}

        <section className="nav">
        <Link href="/" className="logo">
          Travel Guide
        </Link>
        <nav className="links">
          <Link href="/home" className="a">Home</Link>
          <Link href="/destinations" className="a">Destinations</Link>
          <Link href="/about" className="a">About</Link>
          <Link href="/feedback" className="a">Feedback</Link>
        </nav>
      </section>

      </body>

      

    </html>
  );
}
